const elemData = [
  {
    title: "Search engine optimization",
    subtitle: "Learn more",
    bgColor: "",
    textColor: "",
    image: "https://resloup.studio/services/02.svg",
    position: "left",
  },
  {
    title: "Pay per click advertising",
    subtitle: "Learn more",
    bgColor: "bg-[rgb(21,16,16)]",
    textColor: "text-white",
    invert: "invert",
    image: "https://resloup.studio/services/04.svg",
    position: "right",
  },
  {
    title: "Social media marketing",
    subtitle: "Learn more",
    bgColor: "bg-[rgb(21,16,16)]",
    textColor: "text-white",
    invert: "invert",
    image: "https://resloup.studio/services/01.svg",
    position: "left",
  },
  {
    title: "E-mail marketing",
    subtitle: "Learn more",
    bgColor: "",
    textColor: "",
    image: "https://resloup.studio/services/03.svg",
    position: "right",
  },
  {
    title: "Social media marketing",
    subtitle: "Learn more",
    bgColor: "bg-[rgb(21,16,16)]",
    textColor: "text-white",
    invert: "invert",
    image: "https://resloup.studio/services/01.svg",
    position: "left",
  },
  {
    title: "E-mail marketing",
    subtitle: "Learn more",
    bgColor: "",
    textColor: "",
    image: "https://resloup.studio/services/03.svg",
    position: "right",
  },
];
export default elemData;
